AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Vacavoya ${DEPLOYMENT} SRV

Parameters:
  DEPLOYMENT:
    Description: 'Required. Deployment DEPLOYMENT'
    Type: 'String'
  DOMAIN:
    Description: 'Required. Deployment DEPLOYMENT'
    Type: 'String'
  ACMCERTIFICATEARN:
    Description: 'Required. ACMCERTIFICATEARN For CloudFront HTTPSPort'
    Type: 'String' 
  NEXTAPI: 
    Description: 'Required. NextAPI endpoint'
    Type: 'String' 

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 90
    Runtime: python3.10
    MemorySize: 2048
    Environment:
      Variables:
        DEPLOYMENT: !Sub "${DEPLOYMENT}"
        LOGLEVEL: "INFO"
  Api:
    TracingEnabled: True

Conditions:
  isPrdResource: !Equals [!Ref DEPLOYMENT, 'PRD']
  isNotPrdResource: !Not [!Equals [!Ref DEPLOYMENT, 'PRD']]


Resources:
######### SECTION: NEXT #########################
  NextBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub "${DOMAIN}-DWE-src"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: false
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: 'AES256'

  NextOriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub "${DOMAIN}-nextS3OAC" 
        Description: "OAC for accessing the S3 bucket"
        SigningProtocol: sigv4
        SigningBehavior: always
        OriginAccessControlOriginType: s3

  NextOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: OAI for Next static resources in S3 bucket and images

  CloudFront:
    #checkov:skip=CKV_AWS_68: "For demo purposes and to reduce cost, no WAF is configured"
    #checkov:skip=CKV_AWS_174: "CloudFront default certificate sets security policy to TLSv1 regardless"
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
        - Id: nextS3Origin
          DomainName: !GetAtt NextBucket.RegionalDomainName
          OriginAccessControlId: !Ref NextOriginAccessControl  # New OAC reference
          S3OriginConfig:
            OriginAccessIdentity: '' #Specify empty OAI bc using OAC https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-distribution-s3originconfig.html
        - Id: nextAPIGatewayOrigin
          DomainName: !Sub "${NEXTAPI}"
          OriginPath: '/Prod'
          CustomOriginConfig:
            HTTPSPort: '443'
            OriginProtocolPolicy: https-only
        Aliases:
        - !Sub "${DOMAIN}"
        Enabled: 'true'
        Comment: !Sub "dwe_${DEPLOYMENT}"
        HttpVersion: http2
        IPV6Enabled: 'true'
        PriceClass: PriceClass_100
        ViewerCertificate:
          AcmCertificateArn: !Sub "${ACMCERTIFICATEARN}"
          MinimumProtocolVersion: 'TLSv1.2_2019'
          SslSupportMethod: 'sni-only'
        DefaultRootObject: ''
        DefaultCacheBehavior:
          TargetOriginId: nextAPIGatewayOrigin
          ResponseHeadersPolicyId: eaab4381-ed33-4a86-88ca-d9558dc6cd63
          OriginRequestPolicyId: b689b0a8-53d0-40ab-baf2-68738e2966ac # AllViewerExceptHostHeader
          CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad # CachingDisabled
          DefaultTTL: 0
          MaxTTL: 0
          MinTTL: 0
          ForwardedValues:
            QueryString: 'true'
            Cookies:
              Forward: all
          Compress: 'true'
          AllowedMethods:
          - DELETE
          - GET
          - HEAD
          - OPTIONS
          - PATCH
          - POST
          - PUT
          ViewerProtocolPolicy: redirect-to-https
          MaxTTL: '31536000'
        CacheBehaviors:
        - PathPattern: '/_next/static/*'
          TargetOriginId: nextS3Origin
          CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad # CachingDisabled
          AllowedMethods:
          - GET
          - HEAD
          ForwardedValues:
            QueryString: 'false'
            Cookies:
              Forward: none
          Compress: 'true'
          ViewerProtocolPolicy: https-only
        - PathPattern: '/static/*'
          TargetOriginId: nextS3Origin
          CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad # CachingDisabled
          AllowedMethods:
          - GET
          - HEAD
          ForwardedValues:
            QueryString: 'false'
            Cookies:
              Forward: none
          Compress: 'true'
          ViewerProtocolPolicy: https-only
        - PathPattern: '/images/*'  # Changed from /static/*
          TargetOriginId: nextS3Origin
          CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad
          AllowedMethods:
          - GET
          - HEAD
          ForwardedValues:
            QueryString: 'false'
            Cookies:
              Forward: none
          Compress: 'true'
          ViewerProtocolPolicy: https-only

  NextBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref NextBucket
      PolicyDocument:
        Id: NextBucketPolicy
        Version: 2012-10-17
        Statement:
        - Action:
            - 's3:GetObject'
          Effect: Allow
          Principal:
            Service: cloudfront.amazonaws.com
          Resource: !Sub '${NextBucket.Arn}/*'
          Condition:
            StringEquals:
              AWS:SourceArn: !Sub 'arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudFront.Id}'
              